export const ANIME__SET_TOP_ANIMES = 'ANIME__SET_TOP_ANIMES--BL90XriHBX';
export const ANIME__SET_TOP_AIRING_ANIMES = 'ANIME__SET_TOP_AIRING_ANIMES--gMwzUxbNGx';
export const ANIME__SET_TOP_MANGAS = 'ANIME__SET_TOP_MANGAS--hzCVHOlfkI';
export const ANIME__SET_TODAY_ANIMES = 'ANIME__SET_TODAY_ANIMES--QY3xR4K0m0';
export const ANIME__SET_DETAILED = 'ANIME__SET_DETAILED--0kOpfZOyPT';

export const ANIME__GET_DETAILED = 'ANIME__GET_DETAILED--3bQxDQeHkw';
export const ANIME__CLEAR_DETAILED = 'ANIME__CLEAR_DETAILED--4wmQiACFmx';
